<!-- Banner  -->
<section class="contact_us">
    <div class="contact_us_box">
        <div class="contact_us_item">
            <p>Vous recherchez une information ?</p>
            <button>Contactez-nous</button>
        </div>
    </div>
</section>
<!-- Footer  -->
<footer>
    <div class="footer_box">
        <div class="logo">
            <img src="./assets/logo.jpg" alt="logo de JFHOD">
            <p>Journées Francophones d'Hépato-gastroentérologie et d'Oncologie Digestive</p>
        </div>

        <div class="footer_nav_box">
            <nav class="footer_nav">
                <ul>
                    <li><a href="index.php?page=homepage">Accueil</a></li>
                    <li><a href="#">Les JFHOD</a></li>
                    <li><a href="#">Partenaires</a></li>
                    <li><a href="#">Programme</a></li>
                    <li><a href="#">Livre des résumés</a></li>
                    <li><a href="index.php?page=login_registration">Inscription</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="#">Mention légales</a></li>
                    <li><a href="#">RGPD</a></li>
                </ul>
            </nav>

            <nav class="follow_us_nav">
                <ul>
                    <li><a href="#">Suivez-nous</li>
                    <li><a href="#"><i class="fa-brands fa-linkedin-in fa-lg"></i></a></li>
                    <li><a href="#"><i class="fa-brands fa-facebook fa-lg"></i></a></li>
                </ul>
            </nav>
        </div>
    </div>
    <hr>
    <div class="mention_box">
        <p class="mention">Fait avec <i class="fa-solid fa-heart"></i> par CYIM</p>
    </div>
</footer>
