<!-- Header  -->

<header>
    <div class="header_box">
        <img src="./assets/header.jpg" alt="banner">
        <div class="header_buttons">
            <button class="white"><i class="fa-solid fa-power-off"></i> Connectez-vous</button>
            <button class="yellow">Mes JFHOD</button>
        </div>
    </div>
</header>

<!-- Gradient banner  -->

<div class="banner_gradient">
    <div class="banner_gradient_box">
        <p>Journées Francophones d’Hépato-gastroentérologie et d’Oncologie Digestive</p>
    </div>
</div>

<!-- Navbar  -->

<div class="nav_box">
    <nav>
        <ul>
            <li><a href="#">Les JFHOD <i class="fa-solid fa-caret-down"></i></a></li>
            <li><a href="#">Partenaires</a></li>
            <li><a href="#">Programme <i class="fa-solid fa-caret-down"></i></a></li>
            <li><a href="#">Livre des résumés</a></li>
            <li><a href="#">Inscriptions <i class="fa-solid fa-caret-down"></i></a></li>
            <li><a href="#">FAQ</li>
            <li><a href="#">Contacts</a></li>
        </ul>
    </nav>
</div>

<!-- Actualités  -->
<section class="section_news">
    <div class="section_box">
        <article>
            <div class="title">
                <h2>Actualités</h2><div class="line"></div>
            </div>
            <h3>Titre de l'actualité principale sur deux lignes un peu longue au sujet du congrès JFHOD</h3>
            <span class="data"><i class="fa-solid fa-clock"></i> 01 mai 2022</span>

            <p>Lorem ipsum dolor sit amet,<mark>consectetur adipiscing</mark> elit.Morbi eu orci sed odio faucibus cursus.Aenean urna sapien,
                sollicitudin non sollicitudin sed,sollicitudin et metus.Proin eget sodales nisl.In hac habitasse platea dictumst.Ut
                rutrum blandit ipsum.Ut quam velit,tempus at elit eget,<mark>gravida hendrerit</mark> velit.Phasellus auctor ullamcorper nibh sit
                amet pellentesque.<br/><br/>
                Nunc ac rutrum mi,in sagittis velit.Praesent varius nibh ac nunc auctor,sed iaculis dolor laoreet.Vestibulumamaximus
                urna.
            </p>

            <div class="link_box">
                <a href="#" class="yellow_link">Lien sur une ligne1</a>
                <a href="#" class="yellow_link">Lien sur une ligne2</a>
            </div>

            <i class="fa-regular fa-circle-plus"></i>
            <svg class="circle_plus" xmlns="http://www.w3.org/2000/svg" width="20" height="30"viewBox="0 0 512 512"><path d="M0 256C0 114.6 114.6 0 256 0C397.4 0 512 114.6 512 256C512 397.4 397.4 512 256 512C114.6 512 0 397.4 0 256zM256 368C269.3 368 280 357.3 280 344V280H344C357.3 280 368 269.3 368 256C368 242.7 357.3 232 344 232H280V168C280 154.7 269.3 144 256 144C242.7 144 232 154.7 232 168V232H168C154.7 232 144 242.7 144 256C144 269.3 154.7 280 168 280H232V344C232 357.3 242.7 368 256 368z"/></svg>
        </article>
    </div>
    <div class="img_box">
        <img src="./assets/affiche.jpg" alt="affiche">
    </div>
    <div class="background_gradient"></div>
</section>