<!-- Actualités  -->

<section class="section_news">
    <div class="section_box">
        <article>
            <div class="title">
                <h2>Actualités</h2><div class="line"></div>
            </div>
            <h3>Titre de l'actualité principale sur deux lignes un peu longue au sujet du congrès JFHOD</h3>
            <span class="data"><i class="fa-solid fa-clock"></i> 01 mai 2022</span>

            <p>Lorem ipsum dolor sit amet,<mark>consectetur adipiscing</mark> elit.Morbi eu orci sed odio faucibus cursus.Aenean urna sapien,
                sollicitudin non sollicitudin sed,sollicitudin et metus.Proin eget sodales nisl.In hac habitasse platea dictumst.Ut
                rutrum blandit ipsum.Ut quam velit,tempus at elit eget,<mark>gravida hendrerit</mark> velit.Phasellus auctor ullamcorper nibh sit
                amet pellentesque.<br/><br/>
                Nunc ac rutrum mi,in sagittis velit.Praesent varius nibh ac nunc auctor,sed iaculis dolor laoreet.Vestibulumamaximus
                urna.
            </p>

            <div class="link_box">
                <a href="#" class="yellow_link">Lien sur une ligne1</a>
                <a href="#" class="yellow_link">Lien sur une ligne2</a>
            </div>
            <svg class="circle_plus" width="20" height="30" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M432 256c0 17.69-14.33 32.01-32 32.01H256v144c0 17.69-14.33 31.99-32 31.99s-32-14.3-32-31.99v-144H48c-17.67 0-32-14.32-32-32.01s14.33-31.99 32-31.99H192v-144c0-17.69 14.33-32.01 32-32.01s32 14.32 32 32.01v144h144C417.7 224 432 238.3 432 256z"/></svg>
        </article>
    </div>
    <div class="img_box">
        <img src="./assets/affiche.jpg" alt="affiche">
    </div>
    <div class="background_gradient"></div>

    <!-- Aside  -->

    <div class="aside_box">
        <aside class="news_aside">
            <h4>Nom de l'actualité JFHOD sur deux lignes lorem ipsum dolor sit amet,consectetur adipiscing elit spiritum ....</h4>
            <span class="data"><i class="fa-solid fa-clock"></i> 01 mai 2022</span>
            <p>Lorem ipsum dolor sit amet,consectetur adipiscing elit.Sed efficitur uma commodo rutrum ultricies.Donec gravida sed risus in.</p>
            <div class="link_box">
                <a href="#" class="yellow_link">Lien sur une ligne1</a>
            </div>
            <svg class="circle_plus" xmlns="http://www.w3.org/2000/svg" width="20" height="30"viewBox="0 0 512 512"><path d="M0 256C0 114.6 114.6 0 256 0C397.4 0 512 114.6 512 256C512 397.4 397.4 512 256 512C114.6 512 0 397.4 0 256zM256 368C269.3 368 280 357.3 280 344V280H344C357.3 280 368 269.3 368 256C368 242.7 357.3 232 344 232H280V168C280 154.7 269.3 144 256 144C242.7 144 232 154.7 232 168V232H168C154.7 232 144 242.7 144 256C144 269.3 154.7 280 168 280H232V344C232 357.3 242.7 368 256 368z"/></svg>

        </aside>

        <aside class="news_aside">
            <h4>Nom de l'actualité JFHOD sur deux lignes lorem ipsum dolor sit amet,consectetur adipiscing elit spiritum ....</h4>
            <span class="data"><i class="fa-solid fa-clock"></i> 01 mai 2022</span>
            <p>Lorem ipsum dolor sit amet,consectetur adipiscing elit.Sed efficitur uma commodo rutrum ultricies.Donec gravida sed risus in.</p>
            <div class="link_box">
                <a href="#" class="yellow_link">Lien sur une ligne1</a>
            </div>
            <svg class="circle_plus" xmlns="http://www.w3.org/2000/svg" width="20" height="30"viewBox="0 0 512 512"><path d="M0 256C0 114.6 114.6 0 256 0C397.4 0 512 114.6 512 256C512 397.4 397.4 512 256 512C114.6 512 0 397.4 0 256zM256 368C269.3 368 280 357.3 280 344V280H344C357.3 280 368 269.3 368 256C368 242.7 357.3 232 344 232H280V168C280 154.7 269.3 144 256 144C242.7 144 232 154.7 232 168V232H168C154.7 232 144 242.7 144 256C144 269.3 154.7 280 168 280H232V344C232 357.3 242.7 368 256 368z"/></svg>
        </aside>
    </div>
</section>

<!-- Medias  -->

<section class="medias">
    <div class="medias_box">
        <video src="./assets/Les JFHOD 2022.mp4" poster="./assets/poster_video.jpg"></video>

        <div class="media_column">
            <img src="./assets/medias1.jpg" alt="Mes jfhod image">
            <img src="./assets/medias2.jpg" alt="Espace partenaire">
        </div>
    </div>
</section>


<!-- Stats  -->

<section class="stats">
    <div class="stats_background">
          <!-- Caroussel  -->
        <div class="stats_box">
            <div class="slideshow-container">
                <div class="mySlides fade">
                    <img src="./assets/caroussel.jpg">
                </div>

                <div class="mySlides fade">
                    <img src="./assets/caroussel2.jpg">
                </div>

                <a class="prev" onclick="plusSlides(-1)">
                    <svg width="20" height="60" viewBox="0 0 48 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M47.04 7.78312L39.92 0.703125L0.359985 40.3031L39.96 79.9031L47.04 72.8231L14.52 40.3031L47.04 7.78312Z" fill="white"/>
                    </svg>
                </a>    

                <a class="next" onclick="plusSlides(1)">
                    <svg width="20" height="60" viewBox="0 0 48 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M47.04 7.78312L39.92 0.703125L0.359985 40.3031L39.96 79.9031L47.04 72.8231L14.52 40.3031L47.04 7.78312Z" fill="white"/>
                    </svg>
                </a>
            </div>
            <div class="stats_info">
                <h3>Les JFHOD ce sont ...</h3>
                <div class="stats_icons">
                    <div class="icon_item">
                    <i class="fa-thin fa-user fa-2x"></i>
                        <span>1000</span>
                        <p>Participants</p>
                    </div>

                    <div class="icon_item">
                        <i class="fa-thin fa-user fa-2x"></i>
                        <span>1000</span>
                        <p>Intervenant</p>
                    </div>

                    <div class="icon_item">
                        <i class="fa-thin fa-user fa-2x"></i>
                        <span>1000</span>
                        <p>Sessions</p>
                    </div>

                    <div class="icon_item">
                        <i class="fa-thin fa-user fa-2x"></i>
                        <span>1000</span>
                        <p>Résumés</p>
                    </div>
                </div>
                <button>En savoir plus</button>
            </div>
        </div>
    </div>
</section>

<!-- Partners  -->

<section class="partners">
    <h3>Les partenaires scientifiques</h3>
    <div class="partners_box">
        <a class="prev">
            <svg width="20" height="60" viewBox="0 0 48 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M47.04 7.78312L39.92 0.703125L0.359985 40.3031L39.96 79.9031L47.04 72.8231L14.52 40.3031L47.04 7.78312Z" fill="#9B9B9B"/>
            </svg>
        </a> 

        <img src="./assets/partners.jpg" alt="logo de partenaires">
        
        <a class="next">
            <svg width="20" height="60" viewBox="0 0 48 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M47.04 7.78312L39.92 0.703125L0.359985 40.3031L39.96 79.9031L47.04 72.8231L14.52 40.3031L47.04 7.78312Z" fill="#6461A7"/>
            </svg>
        </a>
    </div>
</section>


