<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8"/>
    <!-- <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="seo, referencement, meta,developpement, web"> -->
    <title>CYIM TEST</title>
    <!-- <link rel="icon" type="images/vg" sizes="16x16" href="img/first.svg"> -->
    <!-- Css  -->
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <!-- Font Awesome  -->
    <!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">   -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css">

    <!-- Fonts  -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
  </head>
<body>
  
  <main>
    <?php require $page ?>
  </main>
    
  
</body>
</html>

