<div class="login_page">
    <div class="login_box ">
       <h2> Connectez-vous</h2>
        <form method="POST"  enctype="multipart/form-data">
            <span class='formErrors'><?php if(isset ($errors)){echo $errors;}?></span><br/>
            <input type="email" name="email" placeholder="Email" class="inputs">
            <input type="password" class="hide-pass inputs long-input" name="password" placeholder="Mot de Passe"><br>
            <!-- BUTTON SUBMITT  -->
            <input type="submit" class="inputs submit blue" value="Connexion"><br>
        </form>
    </div>
</div>